window.EV3C_ARTISTS = [
  { name: "Frank Sinatra", type: "person", born: "1915", died: "1998", q: "Frank Sinatra official" },
  { name: "Édith Piaf", type: "person", born: "1915", died: "1963", q: "Edith Piaf official" },
  { name: "Elvis Presley", type: "person", born: "1935", died: "1977", q: "Elvis Presley official" },
  { name: "John Lennon", type: "person", born: "1940", died: "1980", q: "John Lennon official" },
  { name: "Bob Dylan", type: "person", born: "1941", q: "Bob Dylan official" },
  { name: "Paul McCartney", type: "person", born: "1942", q: "Paul McCartney official" },
  { name: "Aretha Franklin", type: "person", born: "1942", died: "2018", q: "Aretha Franklin official" },
  { name: "Jimi Hendrix", type: "person", born: "1942", died: "1970", q: "Jimi Hendrix official" },
  { name: "Julio Iglesias", type: "person", born: "1943", q: "Julio Iglesias official" },
  { name: "Mick Jagger", type: "person", born: "1943", q: "Mick Jagger official" },
  { name: "Joan Manuel Serrat", type: "person", born: "1943", q: "Joan Manuel Serrat official" },
  { name: "Jim Morrison", type: "person", born: "1943", died: "1971", q: "The Doors official" },
  { name: "Janis Joplin", type: "person", born: "1943", died: "1970", q: "Janis Joplin official" },
  { name: "Johnny Hallyday", type: "person", born: "1943", died: "2017", q: "Johnny Hallyday official" },
  { name: "Bob Marley", type: "person", born: "1945", died: "1981", q: "Bob Marley official" },
  { name: "Freddie Mercury", type: "person", born: "1946", died: "1991", q: "Queen official" },
  { name: "Elton John", type: "person", born: "1947", q: "Elton John official" },
  { name: "David Bowie", type: "person", born: "1947", died: "2016", q: "David Bowie official" },
  { name: "Maria del Mar Bonet", type: "person", born: "1947", q: "Maria del Mar Bonet" },
  { name: "Lluís Llach", type: "person", born: "1948", q: "Lluis Llach official" },
  { name: "Robert Plant", type: "person", born: "1948", q: "Led Zeppelin official" },
  { name: "Bruce Springsteen", type: "person", born: "1949", q: "Bruce Springsteen official" },
  { name: "Stevie Wonder", type: "person", born: "1950", q: "Stevie Wonder official" },
  { name: "Sting", type: "person", born: "1951", q: "Sting official" },
  { name: "Prince", type: "person", born: "1958", died: "2016", q: "Prince official" },
  { name: "Madonna", type: "person", born: "1958", q: "Madonna official" },
  { name: "Michael Jackson", type: "person", born: "1958", died: "2009", q: "Michael Jackson official" },
  { name: "Bono", type: "person", born: "1960", q: "U2 official" },
  { name: "Manu Chao", type: "person", born: "1961", q: "Manu Chao official" },
  { name: "Axl Rose", type: "person", born: "1962", q: "Guns N Roses official" },
  { name: "Whitney Houston", type: "person", born: "1963", died: "2012", q: "Whitney Houston official" },
  { name: "Kurt Cobain", type: "person", born: "1967", died: "1994", q: "Nirvana official" },
  { name: "Alejandro Sanz", type: "person", born: "1968", q: "Alejandro Sanz official" },
  { name: "Céline Dion", type: "person", born: "1968", q: "Celine Dion official" },
  { name: "Luis Miguel", type: "person", born: "1970", q: "Luis Miguel official" },
  { name: "-M- Matthieu Chedid", type: "person", born: "1971", q: "Matthieu Chedid official" },
  { name: "Juanes", type: "person", born: "1972", q: "Juanes official" },
  { name: "Enrique Iglesias", type: "person", born: "1975", q: "Enrique Iglesias official" },
  { name: "Shakira", type: "person", born: "1977", q: "Shakira official" },
  { name: "Beyoncé", type: "person", born: "1981", q: "Beyonce official" },
  { name: "Amy Winehouse", type: "person", born: "1983", died: "2011", q: "Amy Winehouse official" },
  { name: "Bruno Mars", type: "person", born: "1985", q: "Bruno Mars official" },
  { name: "Stromae", type: "person", born: "1985", q: "Stromae official" },
  { name: "Lady Gaga", type: "person", born: "1986", q: "Lady Gaga official" },
  { name: "Adele", type: "person", born: "1988", q: "Adele official" },
  { name: "Rihanna", type: "person", born: "1988", q: "Rihanna official" },
  { name: "Taylor Swift", type: "person", born: "1989", q: "Taylor Swift official" },
  { name: "The Weeknd", type: "person", born: "1990", q: "The Weeknd official" },
  { name: "C. Tangana", type: "person", born: "1990", q: "C Tangana official" },
  { name: "Ed Sheeran", type: "person", born: "1991", q: "Ed Sheeran official" },
  { name: "Rosalía", type: "person", born: "1992", q: "Rosalia official" },
  { name: "Bad Bunny", type: "person", born: "1994", q: "Bad Bunny official" },
  { name: "Harry Styles", type: "person", born: "1994", q: "Harry Styles official" },
  { name: "Angèle", type: "person", born: "1995", q: "Angele official" },
  { name: "Dua Lipa", type: "person", born: "1995", q: "Dua Lipa official" },
  { name: "Billie Eilish", type: "person", born: "2001", q: "Billie Eilish official" },
  { name: "Olivia Rodrigo", type: "person", born: "2003", q: "Olivia Rodrigo official" },
  { name: "The Beatles", type: "group", born: "1960", died: "1970", q: "The Beatles official" },
  { name: "The Beach Boys", type: "group", born: "1961", q: "The Beach Boys official" },
  { name: "The Rolling Stones", type: "group", born: "1962", q: "The Rolling Stones official" },
  { name: "The Who", type: "group", born: "1964", q: "The Who official" },
  { name: "The Doors", type: "group", born: "1965", died: "1973", q: "The Doors official" },
  { name: "Pink Floyd", type: "group", born: "1965", q: "Pink Floyd official" },
  { name: "Led Zeppelin", type: "group", born: "1968", died: "1980", q: "Led Zeppelin official" },
  { name: "Black Sabbath", type: "group", born: "1968", q: "Black Sabbath official" },
  { name: "Queen", type: "group", born: "1970", q: "Queen official" },
  { name: "Eagles", type: "group", born: "1971", q: "Eagles official" },
  { name: "ABBA", type: "group", born: "1972", died: "1982", q: "ABBA official" },
  { name: "AC/DC", type: "group", born: "1973", q: "ACDC official" },
  { name: "Kiss", type: "group", born: "1973", q: "KISS official" },
  { name: "Ramones", type: "group", born: "1974", died: "1996", q: "Ramones official" },
  { name: "Sex Pistols", type: "group", born: "1975", died: "1978", q: "Sex Pistols official" },
  { name: "Iron Maiden", type: "group", born: "1975", q: "Iron Maiden official" },
  { name: "The Clash", type: "group", born: "1976", died: "1986", q: "The Clash official" },
  { name: "U2", type: "group", born: "1976", q: "U2 official" },
  { name: "The Police", type: "group", born: "1977", died: "1986", q: "The Police official" },
  { name: "Dire Straits", type: "group", born: "1977", died: "1995", q: "Dire Straits official" },
  { name: "The Cure", type: "group", born: "1978", q: "The Cure official" },
  { name: "Joy Division", type: "group", born: "1976", died: "1980", q: "Joy Division official" },
  { name: "Depeche Mode", type: "group", born: "1980", q: "Depeche Mode official" },
  { name: "R.E.M.", type: "group", born: "1980", died: "2011", q: "REM official" },
  { name: "Metallica", type: "group", born: "1981", q: "Metallica official" },
  { name: "Mecano", type: "group", born: "1981", died: "1998", q: "Mecano official" },
  { name: "Indochine", type: "group", born: "1981", q: "Indochine official" },
  { name: "The Smiths", type: "group", born: "1982", died: "1987", q: "The Smiths official" },
  { name: "Soda Stereo", type: "group", born: "1982", died: "1997", q: "Soda Stereo official" },
  { name: "The Waterboys", type: "group", born: "1983", q: "The Waterboys official" },
  { name: "Red Hot Chili Peppers", type: "group", born: "1983", q: "Red Hot Chili Peppers official" },
  { name: "Héroes del Silencio", type: "group", born: "1984", died: "1996", q: "Heroes del Silencio official" },
  { name: "Guns N' Roses", type: "group", born: "1985", q: "Guns N Roses official" },
  { name: "Radiohead", type: "group", born: "1985", q: "Radiohead official" },
  { name: "Els Pets", type: "group", born: "1985", q: "Els Pets official" },
  { name: "Maná", type: "group", born: "1986", q: "Mana official" },
  { name: "Sopa de Cabra", type: "group", born: "1986", q: "Sopa de Cabra official" },
  { name: "Extremoduro", type: "group", born: "1987", died: "2019", q: "Extremoduro official" },
  { name: "Nirvana", type: "group", born: "1987", died: "1994", q: "Nirvana official" },
  { name: "Green Day", type: "group", born: "1987", q: "Green Day official" },
  { name: "Oasis", type: "group", born: "1991", died: "2009", q: "Oasis official" },
  { name: "Daft Punk", type: "group", born: "1993", died: "2021", q: "Daft Punk official" },
  { name: "Foo Fighters", type: "group", born: "1994", q: "Foo Fighters official" },
  { name: "El Canto del Loco", type: "group", born: "1994", died: "2010", q: "El Canto del Loco official" },
  { name: "Jarabe de Palo", type: "group", born: "1996", died: "2020", q: "Jarabe de Palo official" },
  { name: "Coldplay", type: "group", born: "1996", q: "Coldplay official" },
  { name: "La Oreja de Van Gogh", type: "group", born: "1996", q: "La Oreja de Van Gogh official" },
  { name: "Linkin Park", type: "group", born: "1996", q: "Linkin Park official" },
  { name: "Vetusta Morla", type: "group", born: "1998", q: "Vetusta Morla official" },
  { name: "Estopa", type: "group", born: "1999", q: "Estopa official" },
  { name: "Phoenix", type: "group", born: "1999", q: "Phoenix band official" },
  { name: "Maroon 5", type: "group", born: "2001", q: "Maroon 5 official" },
  { name: "Imagine Dragons", type: "group", born: "2008", q: "Imagine Dragons official" },
  { name: "One Direction", type: "group", born: "2010", died: "2016", q: "One Direction official" },
  { name: "BTS", type: "group", born: "2013", q: "BTS official" },
  { name: "Blackpink", type: "group", born: "2016", q: "BLACKPINK official" }
];
